/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.gui;

/**
 *
 * @author nguye
 */
public class PanelLapHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form PanelLapHoaDon
     */
    public PanelLapHoaDon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrungTam = new javax.swing.JPanel();
        panelThongTinKhachHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnTaoTaiKhoan = new javax.swing.JButton();
        btnDungDiem = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        scrTableKhachHang = new javax.swing.JScrollPane();
        tableThongTinKhachHang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        panelThongTinHoaDon = new javax.swing.JPanel();
        lblMaHoaDon = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        lblMaNhanVien = new javax.swing.JLabel();
        lblMaBan = new javax.swing.JLabel();
        dtpNgayTao = new com.github.lgooddatepicker.components.DateTimePicker();
        txtMaBan = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        lblTenKhachHang = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        scrTableThongTinHoaDon = new javax.swing.JScrollPane();
        tableThongTinHoaDon = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        btnInHoaDon = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 251, 233));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        setLayout(new java.awt.BorderLayout());

        panelTrungTam.setBackground(new java.awt.Color(255, 251, 233));
        panelTrungTam.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        panelThongTinKhachHang.setBackground(new java.awt.Color(255, 251, 233));
        panelThongTinKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelThongTinKhachHang.setPreferredSize(new java.awt.Dimension(560, 628));
        panelThongTinKhachHang.setLayout(new java.awt.BorderLayout(0, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Thông tin khách hàng");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        panelThongTinKhachHang.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel4.setBackground(new java.awt.Color(255, 251, 233));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel4.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel5.setBackground(new java.awt.Color(255, 251, 233));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        jPanel5.add(txtTimKiem, java.awt.BorderLayout.CENTER);

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(btnTimKiem, java.awt.BorderLayout.EAST);

        jPanel4.add(jPanel5, java.awt.BorderLayout.NORTH);

        jPanel7.setBackground(new java.awt.Color(255, 251, 233));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 10, 15));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btnTaoTaiKhoan.setText("Tạo tài khoản");
        jPanel7.add(btnTaoTaiKhoan, java.awt.BorderLayout.EAST);

        btnDungDiem.setText("Dùng điểm");
        jPanel7.add(btnDungDiem, java.awt.BorderLayout.WEST);

        jPanel4.add(jPanel7, java.awt.BorderLayout.SOUTH);

        jPanel6.setBackground(new java.awt.Color(255, 251, 233));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jPanel6.setLayout(new java.awt.BorderLayout());

        tableThongTinKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách hàng", "Điểm tích lũy", "Loại thành viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTableKhachHang.setViewportView(tableThongTinKhachHang);

        jPanel6.add(scrTableKhachHang, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        panelThongTinKhachHang.add(jPanel4, java.awt.BorderLayout.CENTER);

        panelTrungTam.add(panelThongTinKhachHang);

        jPanel2.setBackground(new java.awt.Color(255, 251, 233));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 628));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 251, 233));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin hóa đơn");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        jPanel3.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel8.setBackground(new java.awt.Color(255, 251, 233));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 20, 15));
        jPanel8.setLayout(new java.awt.BorderLayout());

        panelThongTinHoaDon.setBackground(new java.awt.Color(255, 251, 233));

        lblMaHoaDon.setText("Mã hóa đơn:");

        lblNgayTao.setText("Ngày tạo:");

        txtMaHoaDon.setEditable(false);

        lblMaNhanVien.setText("Mã nhân viên:");

        lblMaBan.setText("Mã bàn:");

        txtMaBan.setEditable(false);

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        lblTenKhachHang.setText("Tên khách hàng:");

        txtTenKhachHang.setEditable(false);

        javax.swing.GroupLayout panelThongTinHoaDonLayout = new javax.swing.GroupLayout(panelThongTinHoaDon);
        panelThongTinHoaDon.setLayout(panelThongTinHoaDonLayout);
        panelThongTinHoaDonLayout.setHorizontalGroup(
            panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaHoaDon)
                    .addComponent(lblNgayTao)
                    .addComponent(lblMaBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaBan)
                    .addComponent(dtpNgayTao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(lblTenKhachHang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(lblMaNhanVien)
                        .addGap(18, 18, 18)
                        .addComponent(txtMaNhanVien)))
                .addContainerGap())
        );
        panelThongTinHoaDonLayout.setVerticalGroup(
            panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHoaDon)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayTao)
                    .addComponent(dtpNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTenKhachHang)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBan)
                    .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel8.add(panelThongTinHoaDon, java.awt.BorderLayout.PAGE_START);

        tableThongTinHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTableThongTinHoaDon.setViewportView(tableThongTinHoaDon);

        jPanel8.add(scrTableThongTinHoaDon, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        panelTrungTam.add(jPanel2);

        add(panelTrungTam, java.awt.BorderLayout.CENTER);

        panelButton.setBackground(new java.awt.Color(255, 251, 233));

        btnInHoaDon.setText("In hóa đơn");

        btnTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addComponent(btnTrangChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 920, Short.MAX_VALUE)
                .addComponent(btnInHoaDon))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrangChu)
                    .addComponent(btnInHoaDon))
                .addContainerGap())
        );

        add(panelButton, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhanVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDungDiem;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnTaoTaiKhoan;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTrangChu;
    private com.github.lgooddatepicker.components.DateTimePicker dtpNgayTao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblMaBan;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelThongTinHoaDon;
    private javax.swing.JPanel panelThongTinKhachHang;
    private javax.swing.JPanel panelTrungTam;
    private javax.swing.JScrollPane scrTableKhachHang;
    private javax.swing.JScrollPane scrTableThongTinHoaDon;
    private javax.swing.JTable tableThongTinHoaDon;
    private javax.swing.JTable tableThongTinKhachHang;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
