/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.gui;

/**
 *
 * @author nguye
 */
public class PanelTrangChu extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrangChu
     */
    public PanelTrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongKe = new javax.swing.JPanel();
        cardBanSuDung = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cardBanDatTruoc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardDoanhThu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlBangHoatDong = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        spTableHoatDong = new javax.swing.JScrollPane();
        tblHoatDong = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(807, 600));
        setMinimumSize(new java.awt.Dimension(807, 600));
        setPreferredSize(new java.awt.Dimension(807, 600));
        setLayout(new java.awt.BorderLayout());

        pnlThongKe.setBackground(new java.awt.Color(255, 251, 233));
        pnlThongKe.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 1, 60));
        pnlThongKe.setForeground(new java.awt.Color(255, 255, 255));
        pnlThongKe.setLayout(new java.awt.GridLayout(1, 3, 60, 0));

        cardBanSuDung.setBackground(new java.awt.Color(5, 223, 114));
        cardBanSuDung.setPreferredSize(new java.awt.Dimension(250, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bàn đang sử dụng");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");

        javax.swing.GroupLayout cardBanSuDungLayout = new javax.swing.GroupLayout(cardBanSuDung);
        cardBanSuDung.setLayout(cardBanSuDungLayout);
        cardBanSuDungLayout.setHorizontalGroup(
            cardBanSuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanSuDungLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(cardBanSuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        cardBanSuDungLayout.setVerticalGroup(
            cardBanSuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanSuDungLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlThongKe.add(cardBanSuDung);

        cardBanDatTruoc.setBackground(new java.awt.Color(253, 199, 0));
        cardBanDatTruoc.setPreferredSize(new java.awt.Dimension(250, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bàn đặt trước");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("0");

        javax.swing.GroupLayout cardBanDatTruocLayout = new javax.swing.GroupLayout(cardBanDatTruoc);
        cardBanDatTruoc.setLayout(cardBanDatTruocLayout);
        cardBanDatTruocLayout.setHorizontalGroup(
            cardBanDatTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanDatTruocLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cardBanDatTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        cardBanDatTruocLayout.setVerticalGroup(
            cardBanDatTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanDatTruocLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlThongKe.add(cardBanDatTruoc);

        cardDoanhThu.setBackground(new java.awt.Color(255, 100, 103));
        cardDoanhThu.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doanh thu hôm nay");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");

        javax.swing.GroupLayout cardDoanhThuLayout = new javax.swing.GroupLayout(cardDoanhThu);
        cardDoanhThu.setLayout(cardDoanhThuLayout);
        cardDoanhThuLayout.setHorizontalGroup(
            cardDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDoanhThuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cardDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        cardDoanhThuLayout.setVerticalGroup(
            cardDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDoanhThuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnlThongKe.add(cardDoanhThu);

        add(pnlThongKe, java.awt.BorderLayout.PAGE_START);

        pnlBangHoatDong.setBackground(new java.awt.Color(255, 251, 233));
        pnlBangHoatDong.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        pnlBangHoatDong.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(254, 243, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 30, 30, 20));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(148, 134, 111));
        jLabel7.setText("Hoạt động gần đây");
        jPanel1.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        spTableHoatDong.setBorder(null);

        tblHoatDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Khách hàng", "Khu vực", "Bàn", "Thời gian", "Trạng thái"
            }
        ));
        tblHoatDong.setRowHeight(35);
        tblHoatDong.setSelectionBackground(new java.awt.Color(240, 240, 240));
        tblHoatDong.setShowGrid(false);
        spTableHoatDong.setViewportView(tblHoatDong);

        jPanel1.add(spTableHoatDong, java.awt.BorderLayout.CENTER);

        pnlBangHoatDong.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(pnlBangHoatDong, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardBanDatTruoc;
    private javax.swing.JPanel cardBanSuDung;
    private javax.swing.JPanel cardDoanhThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlBangHoatDong;
    private javax.swing.JPanel pnlThongKe;
    private javax.swing.JScrollPane spTableHoatDong;
    private javax.swing.JTable tblHoatDong;
    // End of variables declaration//GEN-END:variables
}
