/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.GUI;

/**
 *
 * @author nguye
 */
public class PanelTrangChu extends javax.swing.JPanel {

    /**
     * Creates new form PanelTrangChu
     */
    public PanelTrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThongke = new javax.swing.JPanel();
        pnlBangHoatDong = new javax.swing.JPanel();
        cardBanSuDung = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cardBanDatTruoc = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cardDoanhThu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(807, 600));
        setMinimumSize(new java.awt.Dimension(807, 600));
        setPreferredSize(new java.awt.Dimension(807, 600));
        setLayout(new java.awt.BorderLayout());

        pnlThongke.setBackground(new java.awt.Color(255, 251, 233));
        pnlThongke.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 20));
        add(pnlThongke, java.awt.BorderLayout.CENTER);

        pnlBangHoatDong.setBackground(new java.awt.Color(255, 251, 233));
        pnlBangHoatDong.setForeground(new java.awt.Color(255, 255, 255));

        cardBanSuDung.setBackground(new java.awt.Color(5, 223, 114));
        cardBanSuDung.setPreferredSize(new java.awt.Dimension(250, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Bàn đang sử dụng");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");

        javax.swing.GroupLayout cardBanSuDungLayout = new javax.swing.GroupLayout(cardBanSuDung);
        cardBanSuDung.setLayout(cardBanSuDungLayout);
        cardBanSuDungLayout.setHorizontalGroup(
            cardBanSuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanSuDungLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(cardBanSuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        cardBanSuDungLayout.setVerticalGroup(
            cardBanSuDungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanSuDungLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        cardBanDatTruoc.setBackground(new java.awt.Color(253, 199, 0));
        cardBanDatTruoc.setPreferredSize(new java.awt.Dimension(250, 120));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bàn đặt trước");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("0");

        javax.swing.GroupLayout cardBanDatTruocLayout = new javax.swing.GroupLayout(cardBanDatTruoc);
        cardBanDatTruoc.setLayout(cardBanDatTruocLayout);
        cardBanDatTruocLayout.setHorizontalGroup(
            cardBanDatTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanDatTruocLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(cardBanDatTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        cardBanDatTruocLayout.setVerticalGroup(
            cardBanDatTruocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardBanDatTruocLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        cardDoanhThu.setBackground(new java.awt.Color(255, 100, 103));
        cardDoanhThu.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doanh thu hôm nay");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("0");

        javax.swing.GroupLayout cardDoanhThuLayout = new javax.swing.GroupLayout(cardDoanhThu);
        cardDoanhThu.setLayout(cardDoanhThuLayout);
        cardDoanhThuLayout.setHorizontalGroup(
            cardDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDoanhThuLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cardDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        cardDoanhThuLayout.setVerticalGroup(
            cardDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardDoanhThuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBangHoatDongLayout = new javax.swing.GroupLayout(pnlBangHoatDong);
        pnlBangHoatDong.setLayout(pnlBangHoatDongLayout);
        pnlBangHoatDongLayout.setHorizontalGroup(
            pnlBangHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBangHoatDongLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(cardBanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(cardBanDatTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cardDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pnlBangHoatDongLayout.setVerticalGroup(
            pnlBangHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBangHoatDongLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlBangHoatDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cardDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardBanDatTruoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardBanSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(pnlBangHoatDong, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardBanDatTruoc;
    private javax.swing.JPanel cardBanSuDung;
    private javax.swing.JPanel cardDoanhThu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlBangHoatDong;
    private javax.swing.JPanel pnlThongke;
    // End of variables declaration//GEN-END:variables
}
