/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.gui;

/**
 *
 * @author nguye
 */
public class PanelQuanLyBan extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyBan
     */
    public PanelQuanLyBan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnAddTable = new javax.swing.JButton();
        scrTableBan = new javax.swing.JScrollPane();
        tableBan = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 251, 233));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 25, 1));
        pnlHeader.setOpaque(false);
        pnlHeader.setLayout(new java.awt.BorderLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Quản lý thông tin bàn ăn trong nhà hàng");
        pnlHeader.add(lblTitle, java.awt.BorderLayout.WEST);

        btnAddTable.setBackground(new java.awt.Color(143, 126, 101));
        btnAddTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTable.setForeground(new java.awt.Color(255, 255, 255));
        btnAddTable.setText("+ Thêm bàn mới");
        btnAddTable.setBorder(null);
        btnAddTable.setMaximumSize(new java.awt.Dimension(150, 40));
        btnAddTable.setMinimumSize(new java.awt.Dimension(150, 40));
        btnAddTable.setOpaque(true);
        btnAddTable.setPreferredSize(new java.awt.Dimension(150, 40));
        btnAddTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTableActionPerformed(evt);
            }
        });
        pnlHeader.add(btnAddTable, java.awt.BorderLayout.EAST);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        tableBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Số bàn", "Khu vực", "Sức chứa", "Thao tác"
            }
        ));
        tableBan.setRowHeight(35);
        scrTableBan.setViewportView(tableBan);

        add(scrTableBan, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTable;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrTableBan;
    private javax.swing.JTable tableBan;
    // End of variables declaration//GEN-END:variables
}
