/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.gui;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.FlowLayout;
import java.awt.Color;
import javax.swing.BoxLayout;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;


public class PanelDatBan extends javax.swing.JPanel {
	private JTextField textField;

    /**
     * Creates new form PanelDatBan
     */
    public PanelDatBan() {
    	
    	JPanel panelContent = new JPanel();
    	add(panelContent);
    	
    	JPanel panelTimKiem = new JPanel();
    	panelContent.add(panelTimKiem);
    	
    	textField = new JTextField("Tìm kiếm theo số điện thoại");
    	panelTimKiem.add(textField);
    	textField.setColumns(10);
    	
    	JButton btnNewButton = new JButton("Tìm kiếm");
    	btnNewButton.addActionListener(new ActionListener() {
    		public void actionPerformed(ActionEvent e) {
    		}
    	});
    	panelTimKiem.add(btnNewButton);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents
}
