/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.gui;

/**
 *
 * @author nguye
 */
public class PanelLapHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form PanelLapHoaDon
     */
    public PanelLapHoaDon() {
        initComponents();
        customUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTrungTam = new javax.swing.JPanel();
        panelThongTinKhachHang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnTaoTaiKhoan = new javax.swing.JButton();
        btnDungDiem = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        scrTableKhachHang = new javax.swing.JScrollPane();
        tableThongTinKhachHang = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        panelThongTinHoaDon = new javax.swing.JPanel();
        lblMaHoaDon = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        lblMaNhanVien = new javax.swing.JLabel();
        lblMaBan = new javax.swing.JLabel();
        txtMaBan = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        lblTenKhachHang = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        txtNgayTao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbKhuyenMai = new javax.swing.JComboBox<>();
        scrTableThongTinHoaDon = new javax.swing.JScrollPane();
        tableThongTinHoaDon = new javax.swing.JTable();
        panelButton = new javax.swing.JPanel();
        btnInHoaDon = new javax.swing.JButton();
        btnTrangChu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 251, 233));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTrungTam.setBackground(new java.awt.Color(255, 251, 233));
        panelTrungTam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelThongTinKhachHang.setBackground(new java.awt.Color(255, 251, 233));
        panelThongTinKhachHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelThongTinKhachHang.setPreferredSize(new java.awt.Dimension(560, 628));
        panelThongTinKhachHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Thông tin khách hàng");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        panelThongTinKhachHang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 537, -1));

        jPanel4.setBackground(new java.awt.Color(255, 251, 233));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 251, 233));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        jPanel5.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 210, 27));

        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        jPanel5.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, -1, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        jPanel7.setBackground(new java.awt.Color(255, 251, 233));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 10, 15));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTaoTaiKhoan.setText("Tạo tài khoản");
        jPanel7.add(btnTaoTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 3, -1, 30));

        btnDungDiem.setText("Dùng điểm");
        btnDungDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDungDiemActionPerformed(evt);
            }
        });
        jPanel7.add(btnDungDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 3, 90, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 551, 330, 40));

        jPanel6.setBackground(new java.awt.Color(255, 251, 233));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 15));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableThongTinKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khách hàng", "Điểm tích lũy", "Loại thành viên"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTableKhachHang.setViewportView(tableThongTinKhachHang);

        jPanel6.add(scrTableKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 310, 511));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 37, 330, 521));

        panelThongTinKhachHang.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 36, 330, 591));

        panelTrungTam.add(panelThongTinKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, -1));

        jPanel2.setBackground(new java.awt.Color(255, 251, 233));
        jPanel2.setPreferredSize(new java.awt.Dimension(560, 628));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 251, 233));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Thông tin hóa đơn");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 537, -1));

        jPanel8.setBackground(new java.awt.Color(255, 251, 233));
        jPanel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 20, 15));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelThongTinHoaDon.setBackground(new java.awt.Color(255, 251, 233));

        lblMaHoaDon.setText("Mã hóa đơn:");

        lblNgayTao.setText("Ngày tạo:");

        txtMaHoaDon.setEditable(false);

        lblMaNhanVien.setText("Mã nhân viên:");

        lblMaBan.setText("Mã bàn:");

        txtMaBan.setEditable(false);

        txtMaNhanVien.setEditable(false);
        txtMaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhanVienActionPerformed(evt);
            }
        });

        lblTenKhachHang.setText("Tên khách hàng:");

        txtTenKhachHang.setEditable(false);

        txtNgayTao.setEditable(false);

        jLabel3.setText("Khuyến mãi:");

        cbKhuyenMai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKhuyenMaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelThongTinHoaDonLayout = new javax.swing.GroupLayout(panelThongTinHoaDon);
        panelThongTinHoaDon.setLayout(panelThongTinHoaDonLayout);
        panelThongTinHoaDonLayout.setHorizontalGroup(
            panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaHoaDon)
                    .addComponent(lblNgayTao)
                    .addComponent(lblMaBan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaBan)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                    .addComponent(txtNgayTao))
                .addGap(45, 45, 45)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(lblMaNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelThongTinHoaDonLayout.createSequentialGroup()
                        .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenKhachHang)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenKhachHang)
                            .addComponent(cbKhuyenMai, 0, 234, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panelThongTinHoaDonLayout.setVerticalGroup(
            panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaHoaDon)
                    .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaNhanVien)
                    .addComponent(txtMaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayTao)
                    .addComponent(lblTenKhachHang)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaBan)
                    .addComponent(txtMaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel8.add(panelThongTinHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 720, -1));

        tableThongTinHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên món", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrTableThongTinHoaDon.setViewportView(tableThongTinHoaDon);

        jPanel8.add(scrTableThongTinHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 710, 472));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 26, 760, 601));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 628));

        panelTrungTam.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 0, 780, -1));

        add(panelTrungTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        panelButton.setBackground(new java.awt.Color(255, 251, 233));

        btnInHoaDon.setText("In hóa đơn");

        btnTrangChu.setText("Quay lại");

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 903, Short.MAX_VALUE)
                .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(panelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 648, 1120, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDungDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDungDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDungDiemActionPerformed

    private void cbKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbKhuyenMaiActionPerformed

    private void customUI() {
        // Placeholder cho txtTimKiem
        setupPlaceholder(txtTimKiem, "Tìm kiếm khách hàng");

        // Thêm action listener cho button quay lại
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });
    }

    /**
     * Tao placeholder cho TextField
     * Khi focus vao, placeholder bien mat
     * Khi focus out va trong, placeholder xuat hien lai
     */
    private void setupPlaceholder(javax.swing.JTextField textField, String placeholder) {
        java.awt.Color placeholderColor = new java.awt.Color(153, 153, 153);
        java.awt.Color textColor = new java.awt.Color(0, 0, 0);

        // Set text mac dinh va mau
        textField.setText(placeholder);
        textField.setForeground(placeholderColor);

        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                // Khi focus vao, neu la placeholder thi xoa
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(textColor);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                // Khi focus out, neu trong thi hien thi placeholder
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(placeholderColor);
                }
            }
        });
    }

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {
        // Quay lại panel đặt món
        java.awt.Frame parentFrame = (java.awt.Frame) javax.swing.SwingUtilities.getWindowAncestor(this);
        if (parentFrame instanceof MainForm) {
            ((MainForm) parentFrame).goBackToPanelDatMon();
        }
    }

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTimKiemActionPerformed

    private void txtMaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtMaNhanVienActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtMaNhanVienActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDungDiem;
    private javax.swing.JButton btnInHoaDon;
    private javax.swing.JButton btnTaoTaiKhoan;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JComboBox<String> cbKhuyenMai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lblMaBan;
    private javax.swing.JLabel lblMaHoaDon;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelThongTinHoaDon;
    private javax.swing.JPanel panelThongTinKhachHang;
    private javax.swing.JPanel panelTrungTam;
    private javax.swing.JScrollPane scrTableKhachHang;
    private javax.swing.JScrollPane scrTableThongTinHoaDon;
    private javax.swing.JTable tableThongTinHoaDon;
    private javax.swing.JTable tableThongTinKhachHang;
    private javax.swing.JTextField txtMaBan;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayTao;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
