/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.restaurant.quanlydatbannhahang.gui;

/**
 *
 * @author nguye
 */
public class PanelQuanLyThue extends javax.swing.JPanel {

    /**
     * Creates new form PanelQuanLyThue
     */
    public PanelQuanLyThue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnThemLoaiThue = new javax.swing.JButton();
        scrTableThue = new javax.swing.JScrollPane();
        tableThue = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 251, 233));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 60, 20, 60));
        setLayout(new java.awt.BorderLayout());

        pnlHeader.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 25, 1));
        pnlHeader.setOpaque(false);
        pnlHeader.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Quản lý các loại thuế và phí áp dụng cho hóa đơn");
        pnlHeader.add(jLabel1, java.awt.BorderLayout.WEST);

        btnThemLoaiThue.setBackground(new java.awt.Color(143, 126, 101));
        btnThemLoaiThue.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemLoaiThue.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLoaiThue.setText("+ Thêm loại thuế");
        btnThemLoaiThue.setBorder(null);
        btnThemLoaiThue.setMaximumSize(new java.awt.Dimension(150, 40));
        btnThemLoaiThue.setMinimumSize(new java.awt.Dimension(150, 40));
        btnThemLoaiThue.setOpaque(true);
        btnThemLoaiThue.setPreferredSize(new java.awt.Dimension(150, 40));
        btnThemLoaiThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiThueActionPerformed(evt);
            }
        });
        pnlHeader.add(btnThemLoaiThue, java.awt.BorderLayout.EAST);

        add(pnlHeader, java.awt.BorderLayout.PAGE_START);

        tableThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên thuế/phí", "Loại", "Giá trị", "Áp dụng cho", "Trạng thái", "Thao tác"
            }
        ));
        tableThue.setRowHeight(35);
        scrTableThue.setViewportView(tableThue);

        add(scrTableThue, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemLoaiThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemLoaiThueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemLoaiThue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JScrollPane scrTableThue;
    private javax.swing.JTable tableThue;
    // End of variables declaration//GEN-END:variables
}
